// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/config"
	"backend/internal/controller/admin"
	cart2 "backend/internal/controller/cart"
	category2 "backend/internal/controller/category"
	flash2 "backend/internal/controller/flash"
	order2 "backend/internal/controller/order"
	product2 "backend/internal/controller/product"
	user2 "backend/internal/controller/user"
	"backend/internal/pkg/jwt"
	"backend/internal/repository/mysql"
	"backend/internal/repository/redis"
	"backend/internal/router"
	"backend/internal/service/cart"
	"backend/internal/service/category"
	"backend/internal/service/flash"
	"backend/internal/service/order"
	"backend/internal/service/payment"
	"backend/internal/service/product"
	"backend/internal/service/user"
)

// Injectors from wire.go:

func InitApp() (*router.Router, error) {
	appConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	jwtUtil := jwt.NewJWTUtil(appConfig)
	db, err := mysql.InitDB(appConfig)
	if err != nil {
		return nil, err
	}
	userRepository := mysql.NewUserRepository(db)
	userService := user.NewUserService(userRepository, jwtUtil)
	userController := user2.NewUserController(userService)
	productRepository := mysql.NewProductRepository(db)
	client, err := redis.InitRedis(appConfig)
	if err != nil {
		return nil, err
	}
	productCache := redis.NewProductCache(client)
	categoryRepository := mysql.NewCategoryRepository(db)
	productService := product.NewProductService(productRepository, productCache, categoryRepository)
	productController := product2.NewProductController(productService)
	cartRepository := mysql.NewCartRepository(db)
	cartService := cart.NewCartService(cartRepository, productRepository)
	cartController := cart2.NewCartController(cartService)
	orderRepository := mysql.NewOrderRepository(db)
	orderItemRepository := mysql.NewOrderItemRepository(db)
	alipayService, err := payment.NewAlipayService(appConfig)
	if err != nil {
		return nil, err
	}
	orderService := order.NewOrderService(db, orderRepository, orderItemRepository, cartRepository, productRepository, productCache, alipayService)
	orderController := order2.NewOrderController(orderService, alipayService)
	categoryCache := redis.NewCategoryCache(client)
	categoryService := category.NewCategoryService(categoryRepository, categoryCache)
	categoryController := category2.NewCategoryController(categoryService)
	adminController := admin.NewAdminController(productService, categoryService)
	flashRepository := mysql.NewFlashRepository(db)
	flashCache := redis.NewFlashCache(client)
	flashService := flash.NewFlashService(db, appConfig, flashRepository, flashCache, orderRepository, orderItemRepository, productRepository, productCache)
	flashController := flash2.NewFlashController(flashService)
	adminFlashController := flash2.NewAdminFlashController(flashService)
	routerRouter := router.NewRouter(appConfig, jwtUtil, userController, productController, cartController, orderController, categoryController, adminController, flashController, adminFlashController, productService, categoryService, flashService)
	return routerRouter, nil
}
